### ISSUE TITLE
Put goodnotes of mockup on repository

### ISSUE THREAD

**Issue by isaisa002** [Broke-Brokers/soen341_fproject2023#100]
This issue consists of updating the PDF for the Website's mock up every time a change is made

**Comment by isaisa002** [comment]
Have put on the repository the current version of the website's mock up
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/d61a355f-2f1b-4a66-8e11-e9b3f6a8d4a8)

**Comment by isaisa002** [comment]
2 days ago, folder was put in this repository which is wrong
[Broke-Brokers.github.io](https://github.com/Broke-Brokers/Broke-Brokers.github.io).
Folder is now in this repository: [Broke_BRokers-soen341projectF2023](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023) in the principal branch for document branch
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/95dcfc36-ede2-4461-81b9-8b735a6e8d17)

**Comment by RebeccaElusme** [comment]
This issue is now closed since the mockup is automatically updated in the repository in the document branch.
