### ISSUE TITLE
TASK - 3.1.6 Update "offer sent" section of broker "offer" page

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#149]
from : #143 

## TASK DESCRIPTION 

As a broker, I want the "offer sent" section of my "offer" page to update so that I can see a list of the offers I sent .

## ACCEPTANCE CRITERIA

- [x] must match mockup #144
- [x]  Information about offer sent by #147  is added to the table of  offer sent

**Comment by JPEUMZZ** [comment]
See #282 for unit test
The form in #147 creates a new offer in Firebase
The form sets variables BrokerID_transmitter which is use in the page offer to show all the offers that the brokerID= BrokerID_transmitter
