### ISSUE TITLE
TASK - 3.5.3 Create Broker- offers.js page and route from App.js

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#152]
from : #142 

## TASK DESCRIPTION 

As a development team, I want to have a Brokers-offer.js page created to a so that I can add components to it .
As a development team, I want to have a route to Brokers-offer.js page in the url

## ACCEPTANCE CRITERIA

- [x] Create Brokers-offer.js page is src/Pages
- [x] Add a route from react App.js to the Brokers-offer.js page

**Comment by DominiqueProulx** [comment]
@isaisa002  You have done this?

**Comment by isaisa002** [comment]
yes !
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/50c74d9d-1e4c-4927-939f-84561fe5b3be)
