### ISSUE TITLE
TASK - 1.4.12 Create Brokers-Clientsjs   page and route from App.js

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#159]
from #131  and #135

##TASK DESCRIPTION 
TASK - 1.4.12 Create Brokers-Clientsjs   page and route from App.js

As a development team, I want to have a Brokers-clients.js page created to a  so that I can add components to it .
As a development team, I want to have a route to the Brokers-CLients.js page in the url

## ACCEPTANCE CRITERIA
- [ ] Create Brokers-clients.js page is src/Pages
- [ ] Add a route from react App.js to the Brokers-clients.js page

**Comment by isaisa002** [comment]
## AS A TEAM DECISION
### This task wouldn't be implemented since it is not required to display all the clients of a broker in a page
