### ISSUE TITLE
TASK - Update meeting minutes for sprint 3

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#162]
## TASK DESCRIPTION 

As a development team member, I want to log the meeting minutes discussions and decisions items to github so that we can keep track of them 

## ACCEPTANCE CRITERIA

- [x] all meeting minutes for sprint 3 are commited to the repo

**Comment by isaisa002** [comment]
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/9644f305-c710-430e-8bf6-d45cff7a32f5)
