### ISSUE TITLE
AT 4.1 - Sys admin Crud operation on broker

### ISSUE THREAD

**Issue by isaisa002** [Broke-Brokers/soen341_fproject2023#206]
### Issue tracking
This acceptance test is for #37 

### User acceptance flow
1. On sys admin page, admin click on create
2. Fill information 
3. Information added on firebase
4. Click on Edit
5. Information appears in Field and admin modify
6. admin click on save 
7. Information changed in firebase

## UNIT TESTS
CREATE WORK: INFORMATION ADDED IN DATABASE
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/7aff712d-5eb0-41ea-a53f-dd7ef7896b32)
READ WORK: REFRESH AND CAN READ NEW BROKER ON PROFILE
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/6d64eaac-0bda-46a4-ad11-a5d668ed23fb)
UPDATE: TEST FAILED
Modifiy button doesn't put saved information in filed
Update button keeps same information
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/3d32c238-27bd-4fcb-9b5e-d9f0e3d4811e)
DELETE WORK: USER DONT EXIST ON FIREBASE

**Comment by DominiqueProulx** [comment]
I added this task to the wiki for sprint 2
