### ISSUE TITLE
TASK - 0.5.1 Navigation per user type

### ISSUE THREAD

**Issue by DominiqueProulx** [Broke-Brokers/soen341_fproject2023#220]
## Task description : 
as a broke brokers website user , i want a different navigation to appear based on my usertype

Acceptance criteria: 
              [navigation sprint2.pdf](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/files/13198502/navigation.sprint2.pdf)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/cc0e0071-3b7f-4abe-b3b3-e84128618cd7)
updated on 04/11/2023
_Originally posted by @DominiqueProulx in https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/issues/51#issuecomment-1784147882_

**Comment by DominiqueProulx** [comment]
@isaisa002   In the database, what were the associated value for each usertype? I will base the logical tests on these
ex: homeowner =3 , renter =2...
 

Guest =
Homeowner = 
Renter = 
Broker =
System Administrator ? 

#68 @taylcr  we should agree/use the same association so we dont have to go back and modify code afterwards

**Comment by isaisa002** [comment]
Administrator = 1 
Broker = 2 
Homeowner and home renter = 3
I didn't separate them in the database field 

Guest didn't put in database. 

@taylcr Should we have a sign in as guest button in login page and give an user type of 0 ?

**Comment by DominiqueProulx** [comment]
> Administrator = 1 Broker = 2 Homeowner and home renter = 3 I didn't separate them in the database field

Thank you
Tho Homebuyer and renter need to be separated because of the mortage calculator of sprint #4
 
> Guest didn't put in database.
> 
> @taylcr Should we have a sign in as guest button in login page and give an user type of 0 ?

they could also be zero by default and If they sign it their user type change? 
also please see https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/discussions/130#discussioncomment-7475728

**Comment by DominiqueProulx** [comment]
It's done : 

See Unit test issue #226
```
// set the cookie for usertype
//guest = 0 , system admin =1 , broker=2 , homebuyer/renter =3
Cookies.set('usertypeID', '0')

function App() {
const usertype = Cookies.get('usertypeID');

//Navbar rendered depends on usertype
function navbarChoice(){
 console.log(usertype);
  switch(usertype){
   case '0': 
       return <Navbar/>;
    case '1': return <Navbar_SysAdmin />;
    case '2': return <Navbar_Brokers />
    case '3': return <Navbar_Homebuyer/>; 
    default : return <Navbar/>;
   }
}
```
