### ISSUE TITLE
TASK 0.7 - Resolve Firebase Crash

### ISSUE THREAD

**Issue by isaisa002** [Broke-Brokers/soen341_fproject2023#298]
from : #157 #160 #161 

## TASK DESCRIPTION 

As a developer, I want to write Firebase queries that doesn't exceed the free quotas allowed (50k)

**Comment by isaisa002** [comment]
## Error got: Quota exceeded 
A free account of Firebase allows 50k of quotas (reading, writing, deletion)
With the current functions to read data in Firebase, our app goes over the quota just by loading the page. 
This is because every time the page load, each function read all the data contained in our database 
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/6dd86908-41a3-40e6-874b-34efa0a22d18)

**Comment by isaisa002** [comment]
Created another database with another account 
Change the way offer form and offer table reads information from Firebase
## Instead of using getDocs to read all the documents in our firebase, we use snapshot

Taking a snapshot of the database, take a "picture" of all the documents & data in our database. 
Thus our function with snapshot retrieve data asynchronously. This means that we don't get the data immediately; instead, we attach a listener, and when the data changes, you receive a snapshot of the current state data.

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/c4d2c7fd-a32d-4672-b5c4-41af55e604f2)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/a3e35271-09c7-4b02-85e3-0b5a44de8331)

**Comment by isaisa002** [comment]
## FOR EXAMPLE
I have tried to read functions in a new database with test collection. 
The component that I used to test snapshot feature on a new database are the make an offer form and the offer tables
### RELOADING
The number of readings for the database is 248. Reloading the page doesn't affect the number of readings. 
This is because nothing was changed in the database, thus the snapshot stays the same & the function only reads the snapshot not Firebase
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/3f774b65-bd24-4909-9ab9-6f7250ee25ea)


### Changing the snapshot
Creating a new offer with the offer form adds an offer to the database
The writing number of the database only increased of 1 (13 writings to 14 writings)
The readings increased of 4 (248 readings to 252 readings) instead of 50k when our function was reading directly on Firebase

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/2adddabc-8c46-472d-a4f0-bf54c9754042)

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/1ccf60ef-ebf0-4c18-8d51-2d80dca335fa)

**Comment by isaisa002** [comment]
## Re populated database new database
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/8549e28b-f10a-4040-9e56-27b568eb3f11)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/66835a40-7db2-4e06-a174-8554936f22f0)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/6792e241-bffd-4037-881d-7a6e0c59b758)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/2c33b7ef-ab11-435d-943c-d16c9f34fff5)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/68b15486-e195-4846-ba3c-8f4aca545bca)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/a8e2263f-8e13-4ea5-b3b1-ad94e33b20e2)

**Comment by isaisa002** [comment]
Search property connected to snapshot of databse
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/bc5b0b58-bc53-4631-8880-499f353a2f46)
Offer page connected to snapshot of database
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/d4188a2f-4dbc-4e3b-b133-28bd0cf3a210)
Make offer form connected to snapshot of database
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/88f015c5-2f6d-42e0-9910-48da2f9b8fb6)

Search brokers result gallery not connected to snapshot of database
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/18f056b7-d61d-40d3-be56-099da53316ae)

**Comment by isaisa002** [comment]
## Issue not resolved for all components

**Comment by isaisa002** [comment]
After all the deletions, creations and readings I have done on the branch #301, we can see that the number of readings increased slowly and gradually over time compared with our previous database where weren't using snapshot to reads the datas
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/118073058/ac4f0e7d-f031-4334-969e-903872459562)

**Comment by DominiqueProulx** [comment]
Hello! I have questions !

- As of today , Is the new database connection done throught the snapshot merged to the main branch?
- which pages are connected to the "new" database?
- which are not 
- What is working and what is not? 
We'll be able to make a list of what piece of code to look at and the fix

**Comment by JPEUMZZ** [comment]
It's not merged in main yet, there's a pull request for us to review #301

**Comment by DominiqueProulx** [comment]
I am working on branch : #BugFix_firebase-search-brokers_Dominique


I got the broker's database to connect in search for broker page.

-  I am getting the information in the console
-  it's not yet showing up in the cards .
-  But there are no more errors 

![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/75f25c81-0f83-413d-8f7f-26dd42277809)
![image](https://github.com/Broke-Brokers/Broke_BRokers-soen341projectF2023/assets/129322102/a4316593-e134-4cb3-821d-e0cd42311ef7)
